""" adding relationships

Revision ID: 42871387e61d
Revises: 4d90ca786ad7
Create Date: 2021-10-16 14:27:54.376618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42871387e61d'
down_revision = '4d90ca786ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting', 'img',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting', 'img',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
