"""Added description and availability to Posting, image to Book.

Revision ID: 96346505c2cc
Revises: c3d2ba3356d4
Create Date: 2021-12-02 16:45:45.348225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96346505c2cc'
down_revision = 'c3d2ba3356d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('posting', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'available')
    op.drop_column('posting', 'description')
    # ### end Alembic commands ###
